### ISSUE TITLE
Deprecation notice for RPi-GPIO install method during install

### ISSUE THREAD

**Issue by FoxtrotPerry** [FoxtrotPerry/sky-pi#25]
During sky-pi installation, a deprecation notice is shown warning of [GPi.GPIO](https://pypi.org/project/RPi.GPIO/)'s deprecated install method (using a setup.py to install).

This is caused by the [inky package](https://github.com/pimoroni/inky) used to drive the display. But luckily, [they're moving to gpiod](https://github.com/pimoroni/inky/pull/182)! When this PR is all settled and merged in, RPi.GPIO will no longer be around to cause the warning!

For those interested, the python library they seem to be moving towards is called [gpiodevice](https://pypi.org/project/gpiodevice/) and is maintained by the makers of the display used in this project.

**Comment by Gadgetoid** [comment]
> For those interested, the python library they seem to be moving towards is called [gpiodevice](https://pypi.org/project/gpiodevice/) and is maintained by the makers of the display used in this project.

For the record `gpiod` is the actual *as official as it gets* Linux means of accessing GPIO from Python - https://pypi.org/project/gpiod/ - since it packages libgpiod which, in turn, uses the GPIO character device interface (the one which will replace the deprecated GPIO sysfs interface).

`gpiodevice` is intended to be a gpio counterpoint to `i2cdevice` and sweep some common usage patterns into a library to assist in building user-facing, hand-holding drivers/code.

**Comment by FoxtrotPerry** [comment]
@Gadgetoid Thank you for the context! I can't thank you enough for putting so much effort into `gpiodevice` and `inky`. Working with the Inky display has been an absolute delight.

**Comment by FoxtrotPerry** [comment]
Resolved as of [0.11.0](https://github.com/FoxtrotPerry/sky-pi/releases/tag/0.11.0)!
